/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a337aeba-8b53-474d-a3c4-b739a3693d88",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_52UANxEoB",
    "aws_user_pools_web_client_id": "20rg0mdi1nfsbdovhnnbkpfpsb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://b27dzj7535grnb3g62ylhc37x4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zoseda5uwrhvhlnt2ucoj4hi74",
    "aws_user_files_s3_bucket": "kingvideofrontend3e2a34c159f74a3293a25030539d0f74427-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
